SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ZeroRez'

DECLARE @SqlStatement NVARCHAR(MAX)
SELECT @SqlStatement = 
    COALESCE(@SqlStatement, N'') + N'DROP TABLE [ZeroRez].' + QUOTENAME(TABLE_NAME) + N';' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ZeroRez' and TABLE_TYPE = 'BASE TABLE'

PRINT @SqlStatement


SELECT * FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'ZeroRez' AND ROUTINE_TYPE = 'PROCEDURE'

DECLARE @SqlStatementp NVARCHAR(MAX)
SELECT @SqlStatementp = 
    COALESCE(@SqlStatementp, N'') + N'DROP PROCEDURE  [ZeroRez].' + QUOTENAME(ROUTINE_NAME) + N';' + CHAR(13)
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'ZeroRez' AND ROUTINE_TYPE = 'PROCEDURE'

PRINT @SqlStatementp