ALTER PROCEDURE rba.[usp_AutomatedScore]                             
(                              
 @Container NVARCHAR(127),                              
 @FileName NVARCHAR(127)                            
)                              
AS                              
BEGIN 

	BEGIN TRY 
		DECLARE
			@filepath			NVARCHAR(MAX)
			,@SourceContainerURL	NVARCHAR(MAX)
			,@FieldTerminator		NVARCHAR(5)
			,@sql					NVARCHAR(MAX)
			,@tblName				NVARCHAR(MAX)
			,@SubPart				NVARCHAR(MAX)
			,@TableName				NVARCHAR(MAX)
			,@TableRename			NVARCHAR(MAX)
			,@UpdateSQL				NVARCHAR(MAX)

		SET  @tblName =  LEFT(@FileName,8)
		SET  @SubPart =  RIGHT(@tblName,2)	
		SET  @filepath    = @container                              
		SET  @container    = SUBSTRING(RIGHT(@Container, LEN(@Container) - 1) ,1,CHARINDEX('/',RIGHT(@Container, LEN(@Container) - 1))- 1 )                              
		SET  @SourceContainerURL  = 'https://contata.blob.core.windows.net/' + @Container                      
		SET  @FieldTerminator=','

		IF EXISTS(SELECT 1 FROM information_schema.tables WHERE TABLE_SCHEMA = 'rba' AND TABLE_NAME = @tblName)
			BEGIN
				SET @TableName = 'rba.'+@tblName
				SET @SQL =''          
				SET @TableRename=''+@tblName+''+REPLACE(REPLACE(CONVERT(VARCHAR, GETDATE(), 0),' ',''),':','')
				SET @SQL ='SP_RENAME  '+''''+@TableName+''''+','+''''+@TableRename+''''          
				PRINT @SQL           
				EXEC(@SQL)
			END
			PRINT 1
		IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE TABLE_SCHEMA = 'rba' AND TABLE_NAME = @tblName)          
			BEGIN          
				SET @sql= 'CREATE TABLE rba.'+@tblName+'
				(            
				   HHID		VARCHAR(254)          
				  ,INDID	VARCHAR(254)          
				  ,Score	VARCHAR(254)                  
				)'
				EXEC(@sql)
			END
			PRINT 2
		IF EXISTS(SELECT 1 FROM sys.external_data_sources WHERE NAME = @container)                              
			SET @sql ='DROP EXTERNAL DATA SOURCE '+ @container                              
			EXEC SP_EXECUTESQL @sql
			PRINT 2.0
			SET @sql = 'CREATE EXTERNAL DATA SOURCE '+@container+ '                           
			WITH ( TYPE = BLOB_STORAGE, LOCATION = '''+ @SourceContainerURL+''');' 

			EXEC SP_EXECUTESQL @sql                
			PRINT 2.1
			SET @sql=''          
			PRINT 2.2
			SET @sql= 'BULK INSERT rba.'+@tblName+' FROM '''+ @FileName + ''' WITH (DATA_SOURCE = '''+@container+''', FORMAT = ''CSV'', FIELDTERMINATOR  = '''+@FieldTerminator+''', FIRSTROW = 2);'             
			PRINT 2.3
			PRINT @sql           
			EXEC SP_EXECUTESQL @sql
			PRINT 3
		SET @UpdateSQL =           
			'SELECT 
				HHID,          
				INDID, 
				[Score],          
				NTILE(10) OVER(ORDER BY [Score] ASC) ScoreDecile_ASC,          
				NTILE(10) OVER(ORDER BY [Score] DESC) ScoreDecile_DESC          
				INTO rba.tempScoreDecile          
			FROM rba.'+@tblName+'          
			WHERE Score IS NOT NULL'
		EXEC(@UpdateSQL)
		PRINT 4
		SET @UpdateSQL =           
			'UPDATE K          
				SET 
					K.[Score]			 = J.Score, 
					K.[ScoreDecile_ASC]  = J.ScoreDecile_ASC,          
					K.[ScoreDecile_DESC] = J.ScoreDecile_DESC,          
					K.IsProspect_ASC  = CASE 
											WHEN J.ScoreDecile_ASC = 1 THEN 1          
											WHEN J.ScoreDecile_ASC IN (2, 3, 4, 5, 6, 7, 8, 9, 10) THEN 0          
											ELSE NULL 
										END,          
					K.IsProspect_DESC  = CASE 
											WHEN J.ScoreDecile_DESC = 1 THEN 1          
											WHEN J.ScoreDecile_DESC IN (2, 3, 4, 5, 6, 7, 8, 9, 10) THEN 0          
											ELSE NULL 
										END          
			FROM rba.tblPopulationSummary_'+@SubPart+' K           
			JOIN rba.tempScoreDecile J          
			ON 
				K.HHID = J.HHID           
			AND K.INDID = J.INDID'
		EXEC(@UpdateSQL)
		PRINT 5

		DROP TABLE rba.tempScoreDecile 
		PRINT 6


	END TRY

	BEGIN CATCH
		INSERT INTO dbo.LogError (                              
			  objectName                              
			 ,ErrorCode                              
			 ,ErrorDescription                              
			 ,ErrorGenerationTime                                 
			)                              
                              
		SELECT -- autogenerated                                
			OBJECT_NAME(@@PROCID)                                
			,ERROR_NUMBER() AS ErrorCode                                
			,'For File ' + @Container + ' ' + @FileName                              
			+' Error of Severity: ' + CAST (ERROR_SEVERITY() AS VARCHAR (4))                                
			+' and State: ' + CAST (ERROR_STATE() AS VARCHAR (8))                                
			+' occured in Line: ' + CAST (ERROR_LINE() AS VARCHAR (10))                                
			+' with following Message: ' + ERROR_MESSAGE() AS ErrorColumnDescription                                
			,GETDATE()  ErrorGenerationTime                                                
	END CATCH

END
