--exec [ZeroRez].[usp_LoadFlat]'/zerorezsource/ZeroRez-Data.csv','ZeroRez-Data.csv'
CREATE PROCEDURE [ZeroRez].[usp_LoadFlat]
	(
		@Container NVARCHAR(127),
		@FileName NVARCHAR(127)
	)
AS
BEGIN

	BEGIN TRY
		DECLARE
			@Sql					NVARCHAR(MAX),		       
			@filepath    			NVARCHAR(255),          		
			@TableName   			NVARCHAR(127),  			         
			@SourceContainerURL		NVARCHAR(MAX),          
			@ArchiveContainerURL	NVARCHAR(MAX)        			    			    						

		SET		@TableName = 'ZeroRez.ZeroRez_bcp'
		SET  	@filepath    			= @container          
		SET  	@container    			= SUBSTRING(RIGHT(@Container, LEN(@Container) - 1) ,1,CHARINDEX('/',RIGHT(@Container, LEN(@Container) - 1))- 1 )          		         
		SET  	@SourceContainerURL  	= 'https://contata.blob.core.windows.net/' + @Container          
		SET  	@ArchiveContainerURL 	= 'https://contata.blob.core.windows.net/' + REPLACE(@Container,'source','archive')          

		IF EXISTS(SELECT 1 FROM sys.external_data_sources WHERE name = @container)          
			SET @sql ='DROP EXTERNAL DATA SOURCE '+ @container          
			EXEC SP_EXECUTESQL @sql  

		SET @sql = 'CREATE EXTERNAL DATA SOURCE '+@container+ '
			WITH ( TYPE = BLOB_STORAGE, LOCATION = '''+ @SourceContainerURL+''');'  
			EXEC SP_EXECUTESQL @sql

		SET @sql= 'BULK INSERT ' + @TableName + ' FROM '''+ @FileName + ''' WITH (DATA_SOURCE = '''+@container+''', FORMAT = ''CSV'', FIELDTERMINATOR  = '','', FIRSTROW = 2);'          
			EXEC SP_EXECUTESQL @sql 

		IF EXISTS(SELECT 1 FROM sys.external_data_sources WHERE NAME = @container)          
			SET @sql=' DROP EXTERNAL DATA SOURCE '+@container  
			EXEC SP_EXECUTESQL @sql

		SELECT @SourceContainerURL SourceContainerURL          
		SELECT @ArchiveContainerURL ArchiveContainerURL 	

		RETURN 1        
	END TRY

	BEGIN CATCH
		IF EXISTS(SELECT 1 FROM sys.external_data_sources WHERE name = @container )         
		set @sql='DROP EXTERNAL DATA SOURCE '+ @container     
		EXEC SP_EXECUTESQL @sql  
    
		INSERT INTO LogError (          
					objectName          
					,ErrorCode          
					,ErrorDescription          
					,ErrorGenerationTime             
				)          
          
		SELECT -- autogenerated            
			 OBJECT_NAME(@@PROCID)            
			,ERROR_NUMBER() AS ErrorCode            
			,'For File ' + @Container + ' ' + @FileName          
			+' Error of Severity: ' + CAST (ERROR_SEVERITY() AS VARCHAR (4))            
			+' and State: ' + CAST (ERROR_STATE() AS VARCHAR (8))            
			+' occured in Line: ' + CAST (ERROR_LINE() AS VARCHAR (10))            
			+' with following Message: ' + ERROR_MESSAGE() AS ErrorColumnDescription            
			,GETDATE()                              
		RETURN -1 	
	END CATCH 
END	