CREATE TABLE InputOrder
(
	Date DATETIME
	,OrderID VARCHAR(10)
)

INSERT INTO InputOrder
VALUES
('2017/01/02','A')
,('2017/01/31','B')
,('2017/02/01','C')
,('2017/09/01','D')

SELECT DATE, OrderID,RANK() OVER(PARTITION BY MONTH(DATE) ORDER BY DATE) FROM InputOrder

SELECT DATE, OrderID, COUNT(DISTINCT MONTH(DATE))
FROM InputOrder
GROUP BY  DATE, OrderID 

SELECT COUNT(DISTINCT MONTH(DATE)) FROM InputOrder

